-- Script was generated by Devart Entity Developer, Version 7.2.10.0
-- Script date 2024. 04. 14. 10:53:29
-- Target Server: SQL Server
-- Server Version: 2019

-- 
-- Creating a table INSTRUCTORs 
-- 
CREATE TABLE INSTRUCTORs (
   profid INT NOT NULL IDENTITY,
   hash_password NVARCHAR(256) NOT NULL,
   first_name NVARCHAR(50) NOT NULL,
   last_name NVARCHAR(50) NOT NULL,
   department NVARCHAR(50) NOT NULL,
   office NVARCHAR(100) NOT NULL,
   user_status NVARCHAR(25) NOT NULL,
   CONSTRAINT PK_INSTRUCTORs PRIMARY KEY (profid)
)
GO

-- 
-- Creating a table EXAMs 
-- 
CREATE TABLE EXAMs (
   course_id INT NOT NULL IDENTITY,
   title NVARCHAR(120) NOT NULL,
   level NVARCHAR(10) NOT NULL,
   kredit_value INT NOT NULL,
   start_time DATETIME2,
   end_time DATETIME2,
   time_limit INT,
   CONSTRAINT PK_EXAMs PRIMARY KEY (course_id)
)
GO

-- 
-- Creating a table STUDENTs 
-- 
CREATE TABLE STUDENTs (
   neptun_id NVARCHAR(20) NOT NULL,
   hash_password NVARCHAR(256) NOT NULL,
   first_name NVARCHAR(50) NOT NULL,
   last_name NVARCHAR(50) NOT NULL,
   user_status NVARCHAR(25) NOT NULL,
   CONSTRAINT PK_STUDENTs PRIMARY KEY (neptun_id)
)
GO

-- 
-- Creating a table QUESTIONs 
-- 
CREATE TABLE QUESTIONs (
   id INT NOT NULL IDENTITY,
   question NVARCHAR(500) NOT NULL,
   answers NVARCHAR(4000) NOT NULL,
   solution INT NOT NULL,
   point_value INT NOT NULL,
   course_id INT,
   CONSTRAINT PK_QUESTIONs PRIMARY KEY (id),
   CONSTRAINT FK_QUESTIONs_EXAMs_0 FOREIGN KEY (course_id) REFERENCES EXAMs (course_id)
)
GO

-- 
-- Creating a table EXAMs_INSTRUCTORs 
-- 
CREATE TABLE EXAMs_INSTRUCTORs (
   course_id INT NOT NULL,
   profid INT NOT NULL,
   CONSTRAINT PK_EXAMs_INSTRUCTORs PRIMARY KEY (course_id, profid),
   CONSTRAINT FK_EXAMs_INSTRUCTORs_EXAMs_0 FOREIGN KEY (course_id) REFERENCES EXAMs (course_id),
   CONSTRAINT FK_EXAMs_INSTRUCTORs_INSTRUCTORs_1 FOREIGN KEY (profid) REFERENCES INSTRUCTORs (profid)
)
GO

-- 
-- Creating a table STUDENTs_EXAMs 
-- 
CREATE TABLE STUDENTs_EXAMs (
   neptun_id NVARCHAR(20) NOT NULL,
   course_id INT NOT NULL,
   result INT NULL, 
   CONSTRAINT PK_STUDENTs_EXAMs PRIMARY KEY (neptun_id, course_id),
   CONSTRAINT FK_STUDENTs_EXAMs_STUDENTs_0 FOREIGN KEY (neptun_id) REFERENCES STUDENTs (neptun_id),
   CONSTRAINT FK_STUDENTs_EXAMs_EXAMs_1 FOREIGN KEY (course_id) REFERENCES EXAMs (course_id)
)
GO

